/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.11.3
// source: ping_pong.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as ping_pong_pb from './ping_pong_pb';


export class HrmClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorpingServer = new grpcWeb.MethodDescriptor(
    '/Hrm/pingServer',
    grpcWeb.MethodType.UNARY,
    ping_pong_pb.PingRequest,
    ping_pong_pb.PingResponse,
    (request: ping_pong_pb.PingRequest) => {
      return request.serializeBinary();
    },
    ping_pong_pb.PingResponse.deserializeBinary
  );

  pingServer(
    request: ping_pong_pb.PingRequest,
    metadata: grpcWeb.Metadata | null): Promise<ping_pong_pb.PingResponse>;

  pingServer(
    request: ping_pong_pb.PingRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: ping_pong_pb.PingResponse) => void): grpcWeb.ClientReadableStream<ping_pong_pb.PingResponse>;

  pingServer(
    request: ping_pong_pb.PingRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: ping_pong_pb.PingResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Hrm/pingServer',
        request,
        metadata || {},
        this.methodDescriptorpingServer,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Hrm/pingServer',
    request,
    metadata || {},
    this.methodDescriptorpingServer);
  }

}

